# Basic Python
##### Keywords: data type,function, loop, try/except, etc.

##  python cheat sheet (cont.)
1. 'Markdown' format to type formula
1. shift + return   compile
1. esc + dd  delete a cell
1. esc + r + y  clear printed result
1. [*]  in front of a cell means 'running' 
1. use Tab to complete a variable/function


In [1]:
try:
    astr = 'Hello Bob'
    istr = int(astr)
except:
    istr = -1

print('First', istr)

try:
    astr = '123'
    istr = int(astr)
except:
    iter = -1
    
    
print('Second', istr)

First -1
Second 123


In [2]:
try:
    print(x)
except NameError:
    x = -1
    
print(x)

-1


In [6]:
# indentation error
# try does not work
try:
    x = 42
     print('x = ', x)#indentation 
except:
    print(x)

IndentationError: unexpected indent (<ipython-input-6-e446b8d3c4ed>, line 4)

In [5]:
if x > 1 :
    print('More than one')
    if x < 100 : 
        print('Less than 100') 
        
print('All done')

IndentationError: unexpected indent (<ipython-input-5-19fd96504268>, line 3)

In [6]:
# cannot try structural errors.
try:
    x = 42
     print('x = ', x)
except IndentationError:
    print('IndentationError')

IndentationError: unexpected indent (<ipython-input-6-14f026d02864>, line 3)

In [ ]:

#string summation
'123'+'456'

In [1]:
def type_print(x):
    print('value = ', x, ',\n type = ', type(x))

In [9]:
listx = [100.111, 100., float(100), 100, 1e2, 100//1, 100/1]

for x in listx:
    type_print(x)

value =  100.111 ,
 type =  <class 'float'>
value =  100.0 ,
 type =  <class 'float'>
value =  100.0 ,
 type =  <class 'float'>
value =  100 ,
 type =  <class 'int'>
value =  100.0 ,
 type =  <class 'float'>
value =  100 ,
 type =  <class 'int'>
value =  100.0 ,
 type =  <class 'float'>


In [3]:
# function change input value?
# z-variable default
# all defaults last variable(s)
# ordering
def sum(x,y, z=0,w = 0,ifprint = False):
    g = x+y+z+w**2
    if(ifprint):
        print(g)
    return g

x = 1
y = 2
h = sum(x,y,w = -1,ifprint = True)
print(h)

4
4


In [6]:
# while
n = 5
while(n>0):  # need to terminate
    print('while', n)
    n = n-1

print('outside while:', n)


while 5
while 4
while 3
while 2
while 1
outside while: 0


In [7]:
# for loop, changes values?
counter = 0
for i in [1,2,3,4] :
    print('inside for: ', i)
    i = i+2
    print('i+2: ',i)
    counter += 1

# what's i?
print('i outside loop: ',i)
print('counter outside loop: ',counter)

inside for:  1
i+2:  3
inside for:  2
i+2:  4
inside for:  3
i+2:  5
inside for:  4
i+2:  6
i outside loop:  6
counter outside loop:  4


In [8]:
# for loop, changes values?
counter = 0
i = 1
while(i<=4):
    i = i+2
    counter += 1

# what's i?
print('i outside loop: ',i)
print('counter outside loop: ',counter)

i outside loop:  5
counter outside loop:  2


In [9]:
# built-in function range
#for i in range(5): # 0-4
#    print(i)

for i in range(0,10,2): # 0-9, every 2 steps
    print(i)
    
print('\n')
for i in range(0,10,3): # 0-9, every 3 steps
    print(i)

0
2
4
6
8


0
3
6
9


In [ ]:

# use lambda to define function quickly
# this is saying g maps x to x**2
g = lambda x: x**2
g(2)

In [273]:
#use built-in help & dir
#dir(range)
#help(range.count)

In [9]:
x = 'HHTT'
lx = [[x,'HT'],['wh',2],1,'outside']
for le in lx:
    print(le)

['HHTT', 'HT']
['wh', 2]
1
outside


In [12]:
for i in range(0,len(x),2):
    print('ith',i,x[i])


ith 0 H
ith 2 T


In [13]:
k = 0
while(k<len(x)):
    print('kth',k,x[k])
    k += 2

kth 0 H
kth 2 T


In [14]:
lst = list(range(10))
print(lst)
print(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
range(0, 10)


# Exercise 01

We want to set up flipping coin random variable and related event here
## We need ingredients:

1. sample space: $\Omega$
1. random variable $X:\Omega \rightarrow \mathbb{R}$
1. probability function $f$



In [ ]:
#define sample space of flipping one coin:
SS = ['H','T']

#define random variable X on the sample space:
# X(H) = 1, X(T) = 0
def rand_X(s):
    if(s == 'H'):
        return 1
    else:
        return 0

#define probability mass function f associated with X
#probability getting a head = 0.7

def pmf_X(s):
    if(s == 1):
        return 0.7
    else:
        return 0.3

#what is the probability I flip the coin 3 times and get HTH
tosses = 'HTH'
prob = 1
for i in tosses:
    prob *= pmf_X(rand_X(i))
    
print('tosses = ', tosses, ', probability = ', prob)


## coin flipping function

The function should be able to:
1. compute probability
1. deal with error input or corner cases


In [ ]:
def prob(tosses):
    prob = 1
    # assume if does not flip at all, the probability is 1

    if(len(tosses) == 0):
        return 1;
    
    for i in tosses:
    #Other than head or tail, any symbol is not acceptable
        if(i not in SS):
            return 0;
        prob *= pmf_X(rand_X(i))
    print('tosses = ', tosses, ', probability = ', prob)
    return prob



# numpy
must import to be used

In [16]:
import numpy as np #np for short
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

print(a,'\n')
print(a[0][0])


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]] 

1


In [18]:
a = np.array([[1,2,3],[4,5,6]], float)
print(a)

b = np.array([[7,8,9],[2,3,4]], dtype = int)
print(b)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[7 8 9]
 [2 3 4]]


In [19]:
a = np.array([[1,2],[4,5]], float)

c = a
print('Let c = a, c=\n', c)
print('before modify c, a = \n', a)

# if you change value of c a changes as well
c[0][0] = 7
print('after change c, c =\n',c)
print('after change c, a =\n', a)

Let c = a, c=
 [[ 1.  2.]
 [ 4.  5.]]
before modify c, a = 
 [[ 1.  2.]
 [ 4.  5.]]
after change c, c =
 [[ 7.  2.]
 [ 4.  5.]]
after change c, a =
 [[ 7.  2.]
 [ 4.  5.]]


In [20]:
a = np.array([[1,2],[4,5]], float)

c = a.copy()
print('Let c = a.copy(), c=\n', c)
print('before modify c, a = \n', a)

# if you change value of c, a does not change this time
c[0][0] = 7
print('after change c, c =\n',c)
print('after change c, a =\n', a)

Let c = a.copy(), c=
 [[ 1.  2.]
 [ 4.  5.]]
before modify c, a = 
 [[ 1.  2.]
 [ 4.  5.]]
after change c, c =
 [[ 7.  2.]
 [ 4.  5.]]
after change c, a =
 [[ 1.  2.]
 [ 4.  5.]]


In [23]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
# help(reshape) does not work! need to use modulo name np as we : import numpy as np
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

In [31]:
b = np.arange(12).reshape(3,4)
print('b=\n',b)

print('matrix to array:\n', b.flatten()) #does not change c
print('Transpose of matrix:\n', b.T)

b=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
matrix to array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose of matrix:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [39]:
s  = np.array([1,2,3])
st = s.reshape(-1,1)
print('s = ',s, ',  shape = ', s.shape)# 1-d
print('st =\n',st, ',\nshape = \n', st.shape) # 2-d

s =  [1 2 3] ,  shape =  (3,)
st =
 [[1]
 [2]
 [3]] ,
shape = 
 (3, 1)


In [40]:
for i in st:
    type_print(i)

value = 
 [1] , type = 
 <class 'numpy.ndarray'>
value = 
 [2] , type = 
 <class 'numpy.ndarray'>
value = 
 [3] , type = 
 <class 'numpy.ndarray'>


In [41]:
for r in range(0,st.shape[0]):
    for col in range(0,st.shape[1]):
        print(r,col,'th item',st[r][col])

0 0 th item 1
1 0 th item 2
2 0 th item 3


In [6]:
# array iteration
b = np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])